name: Build Develop

on:
  push:
    branches:
      - main #develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Clean project
        run: ./gradlew clean

      - name: Read version name
        id: read_version_name
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version_name'
      - name: Read version code
        id: read_version_code
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version_code'

      - name: Print version code
        run: echo "Version code is ${{ steps.read_version_code.outputs.value }}"
      - name: Print version name
        run: echo "Version name is ${{ steps.read_version_name.outputs.value }}"

#      - name: Assemble
#        run: ./gradlew assembleDebug