name: Tests with main

on:
  workflow_dispatch:
    inputs:
      deploy_to_google_play:
        type: choice
        required: true
        description: Deploy To Google Play (Closed testing)?
        default: "NO"
        options:
          - "YES"
          - "NO"
      message:
        type: string
        required: true
        description: Release Notes
      use-emoji:
        type: boolean
        required: false
        description: Include  emojis

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Use inputs
        run: echo "Message - ${{ github.event.inputs.message }}, Deploy to Google Play - ${{ github.event.inputs.deploy_to_google_play }}, Use emoji - ${{ github.event.inputs.use-emoji }}"


      - name: Extract branch name
        run: |
          branch_name=${GITHUB_REF_NAME}
          echo "The branch name is $branch_name and the deploy flag is ${{ github.event.inputs.deploy_to_google_play }}"


      - name: set env variable
        run: |
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Abort if branch is not a release
#        if: contains('${{ github.event.inputs.deploy_to_google_play }}', 'YES') // Esto deberia funcionar SI O SI
        if: contains(env.BRANCH_NAME, 'release/') == false
        run: |
           echo 'Not a release branch!'
           exit 1


      - name: Just comment
        run: |
          echo "Siguiente paso"



#      - name: Clean project
#        run: ./gradlew clean
#
#      - name: Assemble
#        run: ./gradlew assembleDebug