name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Read version code and name from Properties-file
        id: read_version_name
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'version_name'
      - name: Do something with your bumped release version
        run: echo "This is the version name ${{ steps.read_version_name.outputs.value }}"

      - name: Clean project
        run: ./gradlew clean

      - name: Assemble
        run: ./gradlew assembleDebug
