name: Pull Request

on:
  workflow_dispatch:
    inputs:
      deploy_to_google_play:
        type: choice
        description: Deploy To Google Play?
        required: true
        options:
          - YES
          - NO
      message:
        description: Release Notes
        required: true
      use-emoji:
        type: boolean
        required: false
        description: Include  emojis

  pull_request:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.deploy_to_google_play }}"

#      - name: Clean project
#        run: ./gradlew clean
#
#      - name: Assemble
#        run: ./gradlew assembleDebug
